before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    binary: cuttlefish
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
includes:
  - from_file:
    path: ./Makefile
  - from_file:
    path: ./functions
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
